### ISSUE TITLE
basic rom image for rom chips?

### ISSUE THREAD

**Issue by popolonx** [moriyan6001/X1BASICROM#1]
Do you have basic rom image for these 2764 rom chips? Or how is the rom image constructed from basic disk image? I am planning to replace those 5 ROMs with just two ROM chips, but the rom image content is not clear to me.

**Comment by moriyan6001** [comment]
I don't have a ROM image.

The BASIC booted from this board is the same as CZ-8CB01 (Hu-BASIC). CZ-8CB01 is a cassette tape version of BASIC.
https://ja.wikipedia.org/wiki/Hu-BASIC

The I/O port on this board is assigned to I/O 0E00H-0E03H on X1.
http://www.x1center.org/sdx1/sdx1_0.html
If you specify the address to 0E00H-0E02H, you can read 1 byte of ROM from 0E03H.

The content that can be read here is the same as CZ-8CB01. (8CB01-> CZ-8RB)
http://retropc.net/ohishi/museum/cz8rb.htm

Therefore, any software can be started as long as the reading length, reading destination address, and execution start address are correct.
http://www.retropc.net/mm/x1/CZ-8RB/index.html

(I use Google Translate.)
